version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
    ports:
      - ${PORT}:3001
    restart: always
    volumes:
      - ./src:/enviamelo-challenge/src

  postgres:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB : postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
       PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
     - "80:80"
    depends_on:
      - postgres


  
