version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./src:/enviamelo-challenge/src

  postgres:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB : postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
       PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
       PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
     - "80:80"
    depends_on:
      - postgres


  
